AllCops:
  SuggestExtensions: false
  Exclude:
    - bin/**/*

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - config/environments/*
    - db/schema.rb

Style/Documentation:
    Enabled: false

Style/StringLiterals:
    EnforcedStyle: double_quotes